enum ActivityAction {
  // User Actions
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",

  // Interview Actions
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  INTERVIEW_DELETED = "INTERVIEW_DELETED",

  // Resume Actions
  RESUME_UPLOADED = "RESUME_UPLOADED",
  RESUME_DELETED = "RESUME_DELETED",

  // Payment/Subscription Actions
  SUBSCRIPTION_STARTED = "SUBSCRIPTION_STARTED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  // Admin Actions
  ADMIN_LOGIN = "ADMIN_LOGIN",
  ADMIN_TEMPLATE_CREATED = "ADMIN_TEMPLATE_CREATED",
  ADMIN_USER_DELETED = "ADMIN_USER_DELETED",
}

enum ActivityTarget {
  USER = "USER",
  INTERVIEW = "INTERVIEW",
  RESUME = "RESUME",
  PAYMENT = "PAYMENT",
  INTERVIEW_TEMPLATE = "INTERVIEW_TEMPLATE",
  ADMIN = "ADMIN",
  // Add other models as needed
}
