"use client";

import { useState, useEffect } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { getAIAnswer } from "@/actions/learning-hub-action";
import type { LearningHubQuestion } from "@/actions/learning-hub-action";

export function QuestionCard({ question }: { question: LearningHubQuestion }) {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isAnswerLoading, setIsAnswerLoading] = useState(false);
  const [aiAnswer, setAiAnswer] = useState("");
  const [error, setError] = useState<string | null>(null);

  const handleOpenDialog = async () => {
    setIsDialogOpen(true);
    setIsAnswerLoading(true);
    setAiAnswer("");
    setError(null);

    try {
      // Wait for both the API call and minimum loading time (2 seconds)
      const [result] = await Promise.all([
        getAIAnswer(question.questionId),
        new Promise((resolve) => setTimeout(resolve, 2000)), // Minimum 2 seconds
      ]);

      if (result.success && result.answer) {
        setAiAnswer(result.answer);
      } else {
        setError(result.error || "Failed to load answer");
      }
    } catch (err) {
      console.error("Error fetching AI answer:", err);
      setError("An error occurred while fetching the answer");
    } finally {
      setIsAnswerLoading(false);
    }
  };

  // Reset state when dialog closes
  useEffect(() => {
    if (!isDialogOpen) {
      setAiAnswer("");
      setError(null);
    }
  }, [isDialogOpen]);

  return (
    <>
      <Card className="border-border bg-card transition-all hover:shadow-md hover:dark:border-neutral-700">
        <CardContent className="flex flex-col gap-4 p-6 md:flex-row md:items-center md:justify-between">
          <div className="flex-1">
            <p className="text-lg font-semibold text-foreground">
              {question.questionText}
            </p>
            <div className="mt-3 flex flex-wrap gap-2">
              <Badge variant="secondary">{question.category}</Badge>
              {question.tags.map((tag) => (
                <Badge key={tag} variant="outline">
                  {tag}
                </Badge>
              ))}
            </div>
          </div>
          <Button
            variant="outline"
            className="mt-4 border-emerald-500/20 text-emerald-600 hover:bg-emerald-500/10 hover:text-emerald-700 dark:text-emerald-400 dark:hover:bg-emerald-500/10 dark:hover:text-emerald-300 md:mt-0 bg-transparent"
            onClick={handleOpenDialog}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Show AI Answer
          </Button>
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-2xl h-[550px] flex flex-col">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold">
              AI Generated Answer
            </DialogTitle>
            <DialogDescription>
              This is a sample answer generated by Pravya AI.
            </DialogDescription>
          </DialogHeader>

          {/* ✅ FIXED HEIGHT + SCROLLABLE ANSWER BOX */}
          <div className="flex-1 overflow-y-auto pr-2 py-4 min-h-0">
            {isAnswerLoading ? (
              <div className="space-y-3">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
              </div>
            ) : error ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <p className="text-sm text-destructive mb-2">{error}</p>
                <Button variant="outline" size="sm" onClick={handleOpenDialog}>
                  Try Again
                </Button>
              </div>
            ) : aiAnswer ? (
              <div className="prose prose-sm dark:prose-invert max-w-none text-foreground space-y-3">
                {aiAnswer.split("\n\n").map((para, i) => {
                  // ✅ Convert markdown-like bold & italic
                  let formatted = para
                    .replace(/\*\*\*(.*?)\*\*\*/g, "<b><i>$1</i></b>") // ***bold italic***
                    .replace(/\*\*(.*?)\*\*/g, "<b>$1</b>") // **bold**
                    .replace(/\*(.*?)\*/g, "<i>$1</i>") // *italic*
                    .replace(/^- (.*)/gm, "• $1") // Bullet points
                    .replace(/\n/g, "<br/>"); // Line breaks

                  return (
                    <p
                      key={i}
                      className="text-sm leading-relaxed"
                      dangerouslySetInnerHTML={{ __html: formatted }}
                    />
                  );
                })}
              </div>
            ) : (
              <div className="flex items-center justify-center py-8 text-muted-foreground">
                <p className="text-sm">No answer available</p>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-2 pt-4 border-t border-border">
            <Button variant="ghost" onClick={() => setIsDialogOpen(false)}>
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
