"use client"

import { useState } from "react"
import { Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Skeleton } from "@/components/ui/skeleton"

interface Question {
  id: number
  questionText: string
  category: string
  tags: string[]
}

export function QuestionCard({ question }: { question: Question }) {
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isAnswerLoading, setIsAnswerLoading] = useState(false)
  const [aiAnswer, setAiAnswer] = useState("")

  const handleOpenDialog = () => {
    setIsDialogOpen(true)
    setIsAnswerLoading(true)
    setAiAnswer("")

    const timer = setTimeout(() => {
      const mockAnswers: Record<number, string> = {
        1: "useState is a simpler hook for managing single state values, while useReducer is better for complex state logic with multiple sub-values or when the next state depends on the previous one.\n\n• useState: Best for primitive values\n• useReducer: Best for complex objects or arrays\n\nFor example, useReducer is ideal when you have interdependent state pieces.",
        2: "Next.js provides multiple rendering strategies:\n\n• Static Site Generation (SSG): Pre-render pages at build time\n• Server-Side Rendering (SSR): Render on each request\n• Incremental Static Regeneration (ISR): Update static content without rebuilding\n\nUse getServerSideProps for SSR and getStaticProps for SSG.",
      }

      setAiAnswer(mockAnswers[question.id] || "This is a comprehensive answer to your question.")
      setIsAnswerLoading(false)
    }, 1500)

    return () => clearTimeout(timer)
  }

  return (
    <>
      <Card className="border-border bg-card transition-all hover:shadow-md hover:dark:border-neutral-700">
        <CardContent className="flex flex-col gap-4 p-6 md:flex-row md:items-center md:justify-between">
          <div className="flex-1">
            <p className="text-lg font-semibold text-foreground">{question.questionText}</p>
            <div className="mt-3 flex flex-wrap gap-2">
              <Badge variant="secondary">{question.category}</Badge>
              {question.tags.map((tag) => (
                <Badge key={tag} variant="outline">
                  {tag}
                </Badge>
              ))}
            </div>
          </div>
          <Button
            variant="outline"
            className="mt-4 border-emerald-500/20 text-emerald-600 hover:bg-emerald-500/10 hover:text-emerald-700 dark:text-emerald-400 dark:hover:bg-emerald-500/10 dark:hover:text-emerald-300 md:mt-0 bg-transparent"
            onClick={handleOpenDialog}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Show AI Answer
          </Button>
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold">AI Generated Answer</DialogTitle>
            <DialogDescription>This is a sample answer generated by Pravya AI.</DialogDescription>
          </DialogHeader>

          <div className="py-4 min-h-[200px]">
            {isAnswerLoading ? (
              <div className="space-y-3">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
              </div>
            ) : (
              <div className="prose prose-sm dark:prose-invert max-w-none space-y-3 text-foreground">
                {aiAnswer.split("\n\n").map((paragraph, index) => (
                  <p key={index} className="text-sm leading-relaxed">
                    {paragraph}
                  </p>
                ))}
              </div>
            )}
          </div>

          <div className="flex justify-end gap-2 pt-4 border-t border-border">
            <Button variant="ghost" onClick={() => setIsDialogOpen(false)}>
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
